### PR TITLE
Saving colors in configuration, orange as a new color

### PR DESCRIPTION
**Pull request by v0ltumna**
This adds orange as another color which is usually selectable (ok, its mainly because I usually pick it :) ).
Furthermore the change of colors is now saved into the configuration file.
The behavior of loading the configuration is also changed, only data which is not set will be reset to standard now.

### CODE REVIEW

**Comment by zDEFz** [comment]
But why are there added lines in emptyressource ?

**Comment by v0ltumna** [comment]
What are you referring to exactly? I made changes to the following 6 files:
- gui.cpp, optionSet.cpp, optionSet.h (changing the colors and saving it)
- textures.cpp textures.h, gamePlay.cpp (adding orange)

**Comment by zDEFz** [comment]
Look in optionSet.cpp for example. I don't think there is a reason you have 91 Line changes?

**Comment by v0ltumna** [comment]
As i said I also changed the behavior of loading the configuration a bit, so I introduced the function loadStandardOptions. Which is a small change but leads to many changed lines. The other bigger block is the change in the grid of tetris pieces, so that they dont suggest that color is changed at this point, because it is initialised by the variable colormap now.

**Comment by kroyee** [comment]
This looks great!
Could you change the target of the PR to kroyee:develop, I just added that branch so we can have a 2-step process before things go into master to make sure we don't create new bugs/issues along the way.

**Comment by kroyee** [comment]
There will also need to be some slight modification to the compressor class, and a couple of other places (pushGarbage and clearlines) as garbage lines are identified by looking for a tile with value 8, witch will now be 9.
I can do this though, if you want. Easier for me since I know what places are concerned.

**Pull request closed without merging**
