### PR TITLE
Added Visual Studio 2015 solution

### PR DESCRIPTION
**Pull request by rmcat**
Added a .props file that defines the paths to the external libraries.

Instructions for building from Visual Studio solution
1. Copy ``SpeedBlocks.props.edit`` to ``SpeedBlocks.props``
2. Edit the paths in the file
3. Open solution and select the desired build configuration
4. Build

TODO
- Post build event to copy DLLs to output directory

### CODE REVIEW

**Comment by zDEFz** [comment]
Works for me - with his fork i build x86 and x64 now - both debuggable and with break points.

@kroyee i don't know if you didn't work with visual studio yet but you can hover your variables to see what they have currently saved and step by step stepping through everything :)

https://i.imgur.com/Iw5Krpf.png

**Comment by kroyee** [comment]
Could this override someone's personal settings? 
Maybe we could have links in the wiki for example VS 2015 settings.
This could be applied for the makefile aswell.
To avoid clogging up the main repo.
Any thoughts?

**Comment by zDEFz** [comment]
Make a vs2015 branch? xD

**Comment by rmcat** [comment]
There aren't any settings files in this commit except for the vcxproj.filters file, which is the list of files displayed in Visual Studio's Solution Explorer. That file should be fine to include, but could be excluded.

If the base directory becoming crowded is a concern, the source files could be moved to another directory (eg. src, include).

**Comment by kroyee** [comment]
It's more a general sense of keeping the repository tidy.

Only the things that are relevant to everyone inside. Compiler/tool/configuration specifics can be kept alongside it by adding them to the .gitignore and sharing it in the wiki.

**Pull request merged**
