### PR TITLE
Added basic cmake build functionality 

### PR DESCRIPTION
**Pull request by Noir-**
At the moment it depends on a directory named `TGUI-0.7.3` where the include files are stored. I could only test this on Linux so it might need some additions to work on windows and mac I guess. 

I'll add build instructions to the wiki.

### CODE REVIEW

**Comment by texus** [comment]
I would move the include_directories for SFML and TGUI to below the find_package calls, so that you can just do this:
``` cmake
include_directories(${SFML_INCLUDE_DIR})
include_directories(${TGUI_INCLUDE_DIR})
```

These variables are set after find_package found the libraries and headers.

I would also suggest installing TGUI (running `make install` on linux) so that you don't have to manually specify the include location. If you do have to manually specify the include or lib location (e.g. when running on windows) then you just have to set the SFML_ROOT/TGUI_ROOT in cmake to guide the find_package call to the correct folder.

Edit: Maybe also change "0.7.3" in find_package to "0.7" so that you don't have to update the cmake script every time I push a new patch release.

**Comment by kroyee** [comment]
This looks like a great start. Do you want to implement some of the suggested changes before merge?

**Comment by Noir-** [comment]
Yup, I will fix this before merge. At the moment I'm implementing the bug report server.

**Comment by Noir-** [comment]
I guess I need a new PR for the changes I made so im closing this one.

**Pull request closed without merging**
