### PR TITLE
bugfix for 40#

### PR DESCRIPTION
**Pull request by zDEFz**

### CODE REVIEW

**Comment by kroyee** [comment]
Please refrain from making alot of small syntax changes like this in a pull-request.
It's very hard to get some sort of overview of what has actually been changed.
How to structure the code for best readability is to some extent a question of personal taste, and in a joint project I don't think changing things without discussing it, or for a clear reason is a good idea.

Also the lines 206-219 are not good.

**Comment by zDEFz** [comment]
Git does delete lines and inserts new.
And if you tell me that something is not good please tell me what specific is not good.

I also followed your instructions and inserted the replacement everywhere in the code.

**Comment by kroyee** [comment]
If you look at the diff in this merge, there is +339 (additions) and −270 (deletions).
Only around 40-50 of these are relevant, and the others are changes that you have made by changing for example:
`training=false;`
to
`training = false;`

If you look at the code block of 206-219 it looks like
```
+	if (options->left = (options->right))
 +	{
 +		LeB->connect("pressed", &UI::setKey, this, LeB, std::ref(options->left));
 +		SFKeyToString(options->left, keyname);
 +		LeB->setText(keyname);
 +		GenOpt->add(LeB, "BindLeft");
 +	}
 +	else {
 +		LeB->connect("pressed", &UI::setKey, this, LeB, std::ref(options->left));
 +		SFKeyToString(options->left, keyname);
 +		LeB->setText(keyname);
 +		GenOpt->add(LeB, "BindLeft");
 +	}
```
Now this makes no sense.
It should simply be
```
 +		LeB->connect("pressed", &UI::setKey, this, LeB, std::ref(options->left));
 +		SFKeyToString(options->left, keyname);
 +		LeB->setText(keyname);
 +		GenOpt->add(LeB, "BindLeft");
```

**Comment by zDEFz** [comment]
@kroyee we can not change that.
If you want that everyone persist to your standard we need specialized plugins and stuff.
Please recommend me some.
Our Editor does it automaticially.

Maybe you find a tool that uses your formatting or reformats our code automaticially

**Comment by kroyee** [comment]
You can just turn off pretty listing (reformatting) of code.
I'm not saying I want everyone to conform to my standard, I just want to be able to see what's actually in the pull-request without having to go through 100s of lines of irrelevant code.

**Comment by zDEFz** [comment]
To what editor you are referring to?
We also need a rule for the compiler we use!
And a fixed ruleset...

**Comment by kroyee** [comment]
I'm referring to VS.
Why do we need a rule for the compiler and what is a ruleset?

**Comment by zDEFz** [comment]
**There will be in issue raised but we have to think about it.** **Its rather complex.** 
**Just to mention - abort compiling if there is a formatting error and stuff like this.**
There is a lot we can do.

We also could let our code run to an automated building tool (web interface) which is testing if everything is correct (including formatting and compiling) as step before we can submit pulls.

Using only compiler X because different compilers use another library and stuff.
I can reproduce another error in vs2015.

**But for merely editing purposes i use a seperate editor either visual studio code or sublime.
My whole git directory is seperate.
If i made changes to the code i only overwrite the old file.**

**Git will interpret also new lines as deletion of code and insertion of another line**

My current branch got forked by a friend. He did run my updated code succesful and without problems under linux. But under Windows the problem is still persistent. Basically what you did fix isn't working anymore under windows. I don't know the reason. It was fixed and after a small update it is not anymore.

**Comment by kroyee** [comment]
Here is some info that might help out.

> core.autocrlf
> If you’re programming on Windows and working with people who are not (or vice-versa), you’ll probably run into line-ending issues at some point. This is because Windows uses both a carriage-return character and a linefeed character for newlines in its files, whereas Mac and Linux systems use only the linefeed character. This is a subtle but incredibly annoying fact of cross-platform work; many editors on Windows silently replace existing LF-style line endings with CRLF, or insert both line-ending characters when the user hits the enter key.
> 
> Git can handle this by auto-converting CRLF line endings into LF when you add a file to the index, and vice versa when it checks out code onto your filesystem. You can turn on this functionality with the core.autocrlf setting. If you’re on a Windows machine, set it to true – this converts LF endings into CRLF when you check out code:
> 
> $ git config --global core.autocrlf true
> If you’re on a Linux or Mac system that uses LF line endings, then you don’t want Git to automatically convert them when you check out files; however, if a file with CRLF endings accidentally gets introduced, then you may want Git to fix it. You can tell Git to convert CRLF to LF on commit but not the other way around by setting core.autocrlf to input:
> 
> $ git config --global core.autocrlf input
> This setup should leave you with CRLF endings in Windows checkouts, but LF endings on Mac and Linux systems and in the repository.
> 
> If you’re a Windows programmer doing a Windows-only project, then you can turn off this functionality, recording the carriage returns in the repository by setting the config value to false:
> 
> $ git config --global core.autocrlf false

I don't understand what you are talking about. It's not very complicated at all.
If you make changes, try to keep them understandable. One part in this is making sure the git diff only displays relevant information.

**Comment by zDEFz** [comment]
I try again

**Pull request closed without merging**
